# Generated by Django 3.1.4 on 2021-01-20 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='название товара')),
                ('slug', models.SlugField(max_length=200, verbose_name='slug')),
                ('price', models.DecimalField(decimal_places=1, max_digits=9, verbose_name='цена')),
                ('description', models.TextField(verbose_name='описание')),
                ('photo', models.ImageField(upload_to='')),
                ('diagonal', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='диагональ')),
                ('color', models.CharField(max_length=200, verbose_name='цвет')),
                ('camera', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='камера')),
                ('descript', models.TextField(verbose_name='описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='название товара')),
                ('slug', models.SlugField(max_length=200, verbose_name='slug')),
                ('price', models.DecimalField(decimal_places=1, max_digits=9, verbose_name='цена')),
                ('description', models.TextField(verbose_name='описание')),
                ('photo', models.ImageField(upload_to='')),
                ('diagonal', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='диагональ')),
                ('processor', models.CharField(max_length=200, verbose_name='процессор')),
                ('ram', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='оператива')),
                ('descript', models.TextField(verbose_name='описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
