# Generated by Django 3.1.4 on 2021-01-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210120_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='II',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='descript',
        ),
        migrations.AlterField(
            model_name='notebook',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название товара'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название товара'),
        ),
    ]
