# Generated by Django 3.1.4 on 2021-02-18 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210121_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='descript',
        ),
    ]
