# Generated by Django 3.1.4 on 2021-02-19 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_notebook_descript'),
    ]

    operations = [
        migrations.DeleteModel(
            name='II',
        ),
    ]
