# Generated by Django 3.1.4 on 2021-02-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_delete_ii'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='photo',
            field=models.ImageField(upload_to='products'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='photo',
            field=models.ImageField(upload_to='products'),
        ),
    ]
