# Generated by Django 3.1.4 on 2021-02-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210220_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='notebook',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='цена'),
        ),
        migrations.AddField(
            model_name='notebook',
            name='comment',
            field=models.ManyToManyField(blank=True, to='mainapp.Comment'),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='comment',
            field=models.ManyToManyField(blank=True, to='mainapp.Comment'),
        ),
    ]
