# Generated by Django 3.1.4 on 2021-02-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210222_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='for_anon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=True),
        ),
    ]
