# Generated by Django 3.1.4 on 2021-02-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('mainapp', '0010_my_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='My_User',
        ),
    ]
