# Generated by Django 3.1.4 on 2021-02-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_delete_my_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='finalprice',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='цена всего'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='finalprice',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='финальная цена'),
        ),
    ]
