# Generated by Django 3.1.4 on 2021-02-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20210223_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebook',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='comment',
        ),
    ]
