# Generated by Django 3.1.4 on 2021-03-05 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('STATUS_NEW', 'Новый заказ'), ('STATUS_IN_PROGRESS', 'Заказ в пути'), ('STATUS_READY', 'Заказ готов к получению'), ('STATUS_DELIVERED', 'Заказ доставлен')], default='new', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
