# Generated by Django 3.1.4 on 2021-03-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='will_be_delivered',
            field=models.DateField(null=True, verbose_name='Будет доставлено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
