# Generated by Django 3.1.4 on 2021-03-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20210314_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='will_be_delivered',
            field=models.DateField(choices=False, null=True, verbose_name='Будет доставлено'),
        ),
    ]
