# Generated by Django 3.1.4 on 2021-03-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20210314_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='will_be_delivered',
            field=models.DateTimeField(null=True, verbose_name='Будет доставлено'),
        ),
    ]
