# Generated by Django 3.1.4 on 2021-03-14 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_auto_20210314_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='will_be_delivered',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 16, 23, 36, 757885), null=True, verbose_name='Будет доставлено'),
        ),
    ]
