# Generated by Django 3.1.4 on 2021-03-15 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20210314_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='will_be_delivered',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 19, 18, 23, 3, 999446), null=True, verbose_name='Будет доставлено'),
        ),
    ]
