# Generated by Django 3.1.4 on 2021-03-16 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_auto_20210315_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='will_be_delivered',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 20, 15, 17, 8, 872688), null=True, verbose_name='Будет доставлено'),
        ),
    ]
