# Generated by Django 3.1.4 on 2021-03-16 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_auto_20210316_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='will_be_delivered',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 20, 16, 42, 17, 824471), null=True, verbose_name='Будет доставлено'),
        ),
    ]
