# Generated by Django 3.1.4 on 2021-03-16 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_auto_20210316_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='will_be_delivered',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 20, 17, 2, 26, 201591), null=True, verbose_name='Будет доставлено'),
        ),
    ]
