# Generated by Django 3.1.4 on 2021-03-21 04:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_auto_20210317_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_child',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mainapp.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='will_be_delivered',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 7, 53, 20, 281556), null=True, verbose_name='Будет доставлено'),
        ),
    ]
