# Generated by Django 3.1.4 on 2021-03-21 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_auto_20210321_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=50, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='order',
            name='will_be_delivered',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 10, 14, 56, 903624), null=True, verbose_name='Будет доставлено'),
        ),
    ]
