# Generated by Django 3.1.4 on 2021-03-23 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_auto_20210321_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-time_date',)},
        ),
        migrations.AlterField(
            model_name='order',
            name='will_be_delivered',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 20, 10, 16, 860751), null=True, verbose_name='Будет доставлено'),
        ),
    ]
