# Generated by Django 3.1.4 on 2021-03-26 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_auto_20210323_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='likes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='will_be_delivered',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 6, 24, 25, 87454), null=True, verbose_name='Будет доставлено'),
        ),
    ]
