# Generated by Django 3.1.4 on 2021-04-04 09:38

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0041_auto_20210326_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='will_be_delivered',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 12, 38, 24, 313234), null=True, verbose_name='Будет доставлено'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='like',
        ),
        migrations.AddField(
            model_name='product',
            name='like',
            field=models.ManyToManyField(null=True, related_name='liked_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
