# Generated by Django 3.1.4 on 2021-04-04 11:06

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0042_auto_20210404_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='will_be_delivered',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 14, 6, 37, 808721), null=True, verbose_name='Будет доставлено'),
        ),
        migrations.AlterField(
            model_name='product',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
