# Generated by Django 3.1.5 on 2021-05-23 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_auto_20210404_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='will_be_delivered',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 13, 48, 27, 741489), null=True, verbose_name='Будет доставлено'),
        ),
    ]
