# Generated by Django 3.1.4 on 2021-03-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20210316_1525'),
        ('spec', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryFeature',
            new_name='CategoryFeatures',
        ),
        migrations.RenameModel(
            old_name='FeatureValid',
            new_name='FeaturesValid',
        ),
    ]
