# Generated by Django 3.1.4 on 2021-03-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_auto_20210323_2010'),
        ('spec', '0002_auto_20210316_1525'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoryfeatures',
            unique_together={('category', 'feature_name')},
        ),
        migrations.RemoveField(
            model_name='categoryfeatures',
            name='feature_filter_name',
        ),
    ]
